export const TOOGLE_MENU = 'TOOGLE_MENU';

export const LOADING_START = 'LOADING_START';
export const LOADING_END = 'LOADING_END';

export const SHOW_ERROR = 'SHOW_ERROR';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const CLOSE_MESSAGE = 'CLOSE_MESSAGE';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOFF = 'LOGOFF';
export const STORE_USERS = 'STORE_USERS';

export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS';
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const LOAD_GROUP_STARTED = 'LOAD_GROUP_STARTED';
export const LOAD_GROUP_SUCCESS = 'LOAD_GROUP_SUCCESS';
export const UPDATE_GROUP_FILTERS = 'UPDATE_GROUP_FILTERS';
export const TOOGLE_GROUP_FILTERS = 'TOOGLE_GROUP_FILTERS';
export const UPDATE_GROUP_ORDER = 'UPDATE_GROUP_ORDER';

export const ADD_ACCOUNT_SUCCESS = 'ADD_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const LOAD_ACCOUNT_STARTED = 'LOAD_ACCOUNT_STARTED';
export const LOAD_ACCOUNT_SUCCESS = 'LOAD_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_FILTERS = 'UPDATE_ACCOUNT_FILTERS';
export const TOOGLE_ACCOUNT_FILTERS = 'TOOGLE_ACCOUNT_FILTERS';
export const UPDATE_ACCOUNT_ORDER = 'UPDATE_ACCOUNT_ORDER';

export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const LOAD_CATEGORY_STARTED = 'LOAD_CATEGORY_STARTED';
export const LOAD_CATEGORY_SUCCESS = 'LOAD_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FILTERS = 'UPDATE_CATEGORY_FILTERS';
export const TOOGLE_CATEGORY_FILTERS = 'TOOGLE_CATEGORY_FILTERS';
export const UPDATE_CATEGORY_ORDER = 'UPDATE_CATEGORY_ORDER';

export const ADD_TRANSACTION_SUCCESS = 'ADD_TRANSACTION_SUCCESS';
export const UPDATE_TRANSACTION_SUCCESS = 'UPDATE_TRANSACTION_SUCCESS';
export const DELETE_TRANSACTION_SUCCESS = 'DELETE_TRANSACTION_SUCCESS';
export const LOAD_TRANSACTION_STARTED = 'LOAD_TRANSACTION_STARTED';
export const LOAD_TRANSACTION_SUCCESS = 'LOAD_TRANSACTION_SUCCESS';
export const UPDATE_TRANSACTION_FILTERS = 'UPDATE_TRANSACTION_FILTERS';
export const TOOGLE_TRANSACTION_FILTERS = 'TOOGLE_TRANSACTION_FILTERS';
export const UPDATE_TRANSACTION_ORDER = 'UPDATE_TRANSACTION_ORDER';

export const LOAD_BALANCE_PER_ACCOUNT_STARTED = 'LOAD_BALANCE_PER_ACCOUNT_STARTED';
export const LOAD_BALANCE_PER_ACCOUNT_SUCCESS = 'LOAD_BALANCE_PER_ACCOUNT_SUCCESS';
export const UPDATE_BALANCE_PER_ACCOUNT_FILTERS = 'UPDATE_BALANCE_PER_ACCOUNT_FILTERS';
export const TOOGLE_BALANCE_PER_ACCOUNT_FILTERS = 'TOOGLE_BALANCE_PER_ACCOUNT_FILTERS';
