export const TOOGLE_MENU = 'TOOGLE_MENU';

export const LOADING_START = 'LOADING_START';
export const LOADING_END = 'LOADING_END';

export const SHOW_ERROR = 'SHOW_ERROR';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const CLOSE_MESSAGE = 'CLOSE_MESSAGE';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOFF = 'LOGOFF';

export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS';
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const LOAD_GROUP_STARTED = 'LOAD_GROUP_STARTED';
export const LOAD_GROUP_SUCCESS = 'LOAD_GROUP_SUCCESS';
export const UPDATE_GROUP_FILTERS = 'UPDATE_GROUP_FILTERS';
export const TOOGLE_GROUP_FILTERS = 'TOOGLE_GROUP_FILTERS';
export const UPDATE_GROUP_ORDER = 'UPDATE_GROUP_ORDER';
